### ISSUE TITLE
something broke

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#13]

**Comment by Navyguy330** [comment]
not removing posts and not sending pokemon

**Comment by Navyguy330** [comment]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 93, in on_message
    print(log_message)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 70-75: character maps to <undefined>
Message has been deleted: blastoise 45.472497052303275,9.175912141799927 - Author: Arikitos
Message has been deleted: snorlax 58% -37.80540050563382,144.97970581054688 - Author: asdasd
Message has been deleted: [4:34:29 PM] Looking for a Nidoking at -27.4727245, 153.0234501.
[4:34:34 PM] Nidoking got away.
 - CP: 1441
 - IV: 49.4620218406602
 - Move 1: FuryCutterFast
 - Move 2: Earthquake - Author: ShinLevia
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 93, in on_message
    print(log_message)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 72-77: character maps to <undefined>
Message has been deleted: snorlax -37.80540050563382,144.97970581054688 - Author: asdasd

**Comment by Navyguy330** [comment]
i think its jsut log error

**Comment by Navyguy330** [comment]
I GREATLY appreciate all this, yo are doing a GREAT job

**Comment by Navyguy330** [comment]
It is deleting essage has been deleted: 43.682892 ,-79.347038 Porygon 95 IV - Author: pikachu
Message has been deleted: 43.682892 ,-79.347038 Porygon 95 IV - Author: anaz
Message has been deleted: porygon 95 iv 43.682892 ,-79.347038 - Author: CoreComplex
Ignoring exception in on_message

things I think should be allowed.  its close enough to format.

**Comment by Navyguy330** [comment]
shit i missed 2719 dragonite, thanks anyway RAM ❤
loaderka - Today at 5:45 AM
i catch him
NEW MESSAGES
Ram - Today at 5:45 AM
what lvl are you guys


missing these too

**Comment by enjoy2000** [comment]
There is extra space on those `lat/long`, should not be valid if we copy them to `Poke Sniper Bot`, so I think just delete it and people will be more carefully later when posting coord.

About missing messages because the bot is slow I think, and when it was scrawling, it won't be able to manage messages.

**Comment by enjoy2000** [comment]
But I need more time to check it carefully anw

**Comment by Navyguy330** [comment]
ok  thanks tho
