### ISSUE TITLE
Issues with long runtimes

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#15]
Some sort of auto restart would be great.

**Comment by enjoy2000** [comment]
As I said I'm not familiar with `window`, but in `Linux` there are many ways to `monitor processes`.
You can use that keyword to figure what to do for `window`.

**Comment by Navyguy330** [comment]
I know that, but hard to have scripts run, but I mean the code doesnt seem very stable  if it cant run indefinitely.
