### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by myfirstevercode** [enjoy2000/discord-pokemon-go-snipe-bot#21]
Sorry im having this problem..

already installed everything even the discord bot i was going to use but when i tried running bot.py i get this

http://prntscr.com/bzf8so

**Comment by pogoKA** [comment]
me too, same issues

**Comment by enjoy2000** [comment]
You need `Python 3.4.2+`

**Comment by pogoKA** [comment]
yes. i python3.4.2+
