### ISSUE TITLE
Fixxxxxxxxxxxxxxxx, thanks

### ISSUE THREAD

**Issue by pogoKA** [enjoy2000/discord-pokemon-go-snipe-bot#22]
Fixxxxxxxxxxxxxxxx, thanks

**Comment by enjoy2000** [comment]
Did u use `python3 bot.py` ?

And please give me your `python3 --version` output.

**Comment by pogoKA** [comment]
http://imgur.com/a/TPm6P

version down grade ?

**Comment by pogoKA** [comment]
C:\Users\JaeHyuk>python -v
import _frozen_importlib # frozen
import _imp # builtin
import sys # builtin
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\encodings\__pycache__\__init__.cpython-35.pyc ma
tches C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\encodings\__init__.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\encodings\\__pycache_
_\\__init__.cpython-35.pyc'
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\codecs.cpython-35.pyc matches C:\Use
rs\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\codecs.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\codecs.c
python-35.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000005B4FD0>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\encodings\__pycache__\aliases.cpython-35.pyc mat
ches C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\encodings\aliases.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\encodings\\__pycache_
_\\aliases.cpython-35.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000006D7DA0>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000005B46D8>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\encodings\__pycache__\mbcs.cpython-35.pyc matche
s C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\encodings\mbcs.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\encodings\\__pycache_
_\\mbcs.cpython-35.pyc'
import 'encodings.mbcs' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000006E5CF8>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\encodings\__pycache__\utf_8.cpython-35.pyc match
es C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\encodings\utf_8.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\encodings\\__pycache_
_\\utf_8.cpython-35.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000006D8198>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\encodings\__pycache__\latin_1.cpython-35.pyc mat
ches C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\encodings\latin_1.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\encodings\\__pycache_
_\\latin_1.cpython-35.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000006D8438>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\io.cpython-35.pyc matches C:\Users\J
aeHyuk\AppData\Local\Programs\Python\Python35\lib\io.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\io.cpyth
on-35.pyc'
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\abc.cpython-35.pyc matches C:\Users\
JaeHyuk\AppData\Local\Programs\Python\Python35\lib\abc.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\abc.cpyt
hon-35.pyc'
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\_weakrefset.cpython-35.pyc matches C
:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\_weakrefset.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\_weakref
set.cpython-35.pyc'
import '_weakrefset' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000006F0128>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000006D8908>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000006D86A0>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\encodings\__pycache__\cp949.cpython-35.pyc match
es C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\encodings\cp949.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\encodings\\__pycache_
_\\cp949.cpython-35.pyc'
import '_codecs_kr' # <class '_frozen_importlib.BuiltinImporter'>
import '_multibytecodec' # <class '_frozen_importlib.BuiltinImporter'>
import 'encodings.cp949' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000006F9828>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\site.cpython-35.pyc matches C:\Users
\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\site.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\site.cpy
thon-35.pyc'
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\os.cpython-35.pyc matches C:\Users\J
aeHyuk\AppData\Local\Programs\Python\Python35\lib\os.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\os.cpyth
on-35.pyc'
import 'errno' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\stat.cpython-35.pyc matches C:\Users
\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\stat.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\stat.cpy
thon-35.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000007A2320>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\ntpath.cpython-35.pyc matches C:\Use
rs\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\ntpath.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\ntpath.c
python-35.pyc'
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\genericpath.cpython-35.pyc matches C
:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\genericpath.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\genericp
ath.cpython-35.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000007B20F0>
import 'ntpath' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000007A2668>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\_collections_abc.cpython-35.pyc matc
hes C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\_collections_abc.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\_collect
ions_abc.cpython-35.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000007B2710>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x0000000000706160>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\_sitebuiltins.cpython-35.pyc matches
 C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\_sitebuiltins.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\_sitebui
ltins.cpython-35.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x0000000000706518>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\sysconfig.cpython-35.pyc matches C:\
Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\sysconfig.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\sysconfi
g.cpython-35.pyc'
import 'sysconfig' # <_frozen_importlib_external.SourceFileLoader object at 0x0000000000706A90>
# C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\__pycache__\_bootlocale.cpython-35.pyc matches C
:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\_bootlocale.py
# code object from 'C:\\Users\\JaeHyuk\\AppData\\Local\\Programs\\Python\\Python35\\lib\\__pycache__\\_bootloc
ale.cpython-35.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000007EE668>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x00000000006F9C18>
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
>>>

**Comment by enjoy2000** [comment]
use command `python bot.py` pls, u missing `python`

**Comment by pogoKA** [comment]
http://imgur.com/a/PUbky

**Comment by enjoy2000** [comment]
Can u type _python bot.by_?

**Comment by pogoKA** [comment]
yes, i type bot.by     http://imgur.com/a/PUbky

**Comment by pogoKA** [comment]
http://imgur.com/a/MO6Kr

**Comment by pogoKA** [comment]
add bot : http://imgur.com/a/u2U1q

**Comment by pogoKA** [comment]
bot.py http://imgur.com/a/MO6Kr

**Comment by pogoKA** [comment]
why get permissionError ?

**Comment by enjoy2000** [comment]
Yes, you need create role with `Manage Messages` selected and add that role to your bot.

**Comment by ramadadar** [comment]
hey i have the same problem, can you please help me ? i have python 3.4.2

**Comment by ramadadar** [comment]
my config : http://i.imgur.com/CKP9nga.png

**Comment by ramadadar** [comment]
bot auth : http://i.imgur.com/wQu3giU.png

**Comment by enjoy2000** [comment]
> Yes, you need create role with Manage Messages selected and add that role to your bot.

**Comment by ramadadar** [comment]
i mean i get Invalid Syntax line:45 too , i already set manage messages

**Comment by ramadadar** [comment]
here the error : http://i.imgur.com/ni1kci2.png

**Comment by enjoy2000** [comment]
Send me the output of _pyhon --version_ and _pip list_

**Comment by ramadadar** [comment]
@enjoy2000  http://i.imgur.com/LIWWLPJ.png

**Comment by enjoy2000** [comment]
Can u upgrade and try with 3.5?

**Comment by ramadadar** [comment]
ok problem solved but why it wont give me any message when i start the bot ? it like loading but didnt give any respond

http://i.imgur.com/YgivkEm.png

**Comment by pogoKA** [comment]
i bot add  Manage Messages
but get permissionError.

**Comment by pogoKA** [comment]
c:\>python discord-pokemon-go-snipe-bot\bot.py
__main__
Traceback (most recent call last):
  File "discord-pokemon-go-snipe-bot\bot.py", line 20, in <module>
    logging.basicConfig(filename = 'messages.log', level = logging.WARNING)
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1744, in basicC
onfig
    h = FileHandler(filename, mode)
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1008, in __init
__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\JaeHyuk\AppData\Local\Programs\Python\Python35\lib\logging\__init__.py", line 1037, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
OSError: [Errno 22] Invalid argument: 'c:\\messages.log'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x00000000036BE4E0>

c:\>

**Comment by Navyguy330** [comment]
make sure the role it has also has manage messages, or hell do what I did and just give it an admin roll

**Comment by enjoy2000** [comment]
U need to create `C:\messages.log`. I have no idea why in window it need to be placed there.
