### ISSUE TITLE
keep getting this error now - messages being removed, has all the required roles and permissions

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#28]
Message has been deleted: 38.189,128.591 Hypno - Author: roar
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.py",
 line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 131, in on_message
    print(log_message)
  File "C:\Program Files (x86)\Python35-32\lib\encodings\cp437.py", line 19, in
encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 27-30: c
haracter maps to <undefined>
Message has been deleted: [10:40:58] Looking for a Snorlax at 4,7260593303564, -
74,113948205361.
[10:41:00] Using a RazzBerry.
[10:41:00] We caught a Snorlax.
 - CP: 695
 - IV: 92,7892890723442
 - Move 1: ZenHeadbuttFast
 - Move 2: HyperBeam - Author: SliceOfLife
Ignoring exception in on_message

**Comment by pogoKA** [comment]
you use windows ?

**Comment by Navyguy330** [comment]
Yes. It's working but still getting this errors, also it's not spitting out
Pokemon and chords. Is sending the message tho

**Comment by enjoy2000** [comment]
The black circles are special characters so they cause error, but not big problem I think
