### ISSUE TITLE
what is casuing this error? please   its alos not showing the coords

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#29]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.p
 line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 135, in on_message
    await client.delete_message(message)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\client.p
 line 934, in delete_message
    yield from self.http.delete_message(channel.id, message.id, guild_id)
  File "C:\Program Files (x86)\Python35-32\lib\site-packages\discord\http.py"
ine 133, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Missing Permissions

**Comment by enjoy2000** [comment]
No permission, someone removed the role

**Comment by Navyguy330** [comment]
But it's still doing what it needs and I have already added the role back.

**Comment by Navyguy330** [comment]
still isnt posting the coords from the pokesnipers.com has admin and ALL roles now.

**Comment by enjoy2000** [comment]
I separated crawler to other instance please start other instance `python3 bot.py scrawl`

**Comment by Navyguy330** [comment]
Oh OK shit thanks

**Comment by Navyguy330** [comment]
Anyway to have that particular scrawl not also post the message I wanted
scrawl. Lol. Sorry I greatly appreciate all of this ,. I will be sending
donation your way very soon.

**Comment by enjoy2000** [comment]
Sorry I don’t get it

**Comment by Navyguy330** [comment]
Nvm it was just weird timing twice in a row.  The next time it wasn't at
the same time lol
