### ISSUE TITLE
Bot is not removing these large posts??

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#34]
Pokemon: dragonite
Latitude, Longitude: -33,890446, 151.233246
-33.890446, 151.233246
[3:47:04 PM] Looking for a Dragonite at -33.890446, 151.233246.
[3:47:07 PM] Using a RazzBerry.
[3:47:07 PM] We caught a Dragonite.
 - CP: 989
 - IV: 91.6101143830495
 - Move 1: DragonBreathFast
 - Move 2: DragonClaw'

I don't know why it lets those come thru

**Comment by enjoy2000** [comment]
![image](https://cloud.githubusercontent.com/assets/3882619/17286495/8d249ae0-57fc-11e6-87a6-d15d724ec19b.png)
Mine is fine.

**Comment by Navyguy330** [comment]
It does some but sometimes misses it. No biggie guess.
