### ISSUE TITLE
Wrong pokemon name in trackemon

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#39]
C:\Scrawler>python bot.py trackemon
Scrawling Trackemon..
http://www.trackemon.com/fetch/rare?pokedexTypeId=143&sessionId=1579f696627fad
http://www.trackemon.com/fetch/rare?pokedexTypeId=149&sessionId=1579f6967eefd3
http://www.trackemon.com/fetch/rare?pokedexTypeId=59&sessionId=1579f696bd6268
Wrong pokemon name

then quits

**Comment by enjoy2000** [comment]
Show your config, absolutely you put wrong name there

**Comment by Navyguy330** [comment]
i got it,  but the token keeps expriing or omsthing, i have to get a new token every day if not sooner,
