### ISSUE TITLE
OK got it working anyway to ignore all message from admins and mods???

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#4]
It def needs to leave mod and admin messages left alone anyway?

**Comment by Navyguy330** [comment]
ALso would love to add Move sets as well if possible

**Comment by Navyguy330** [comment]
also its only working in the one channel, even though I added another (spelling is good)

**Comment by enjoy2000** [comment]
Can I see your config? Because as I have just tested, it works.
