### ISSUE TITLE
trackemon is not tracking

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#40]
I have it set to 60 seconds but it never grabs anything been 20 mins now and has only posted one.

**Comment by enjoy2000** [comment]
60s is for each pokemon :D
because it takes time to fetch it, so I just put `number_of_pokemons * delay`
Will update later

**Comment by Navyguy330** [comment]
What you mean? Like if I have 10 Pokemon in list. The. What?    If that's
the case I should see like 10

**Comment by enjoy2000** [comment]
If you have 10 pokemons and your delay config is 60, so u need to wait 10 minutes each time.

**Comment by Navyguy330** [comment]
oh shit
weird ok lol  meaning they would be usless by then lol.  kind of odd way to do it
so 1 second is the smallest?

**Comment by enjoy2000** [comment]
Let’s try it, not fully tested yet.

**Comment by Navyguy330** [comment]
yeah not pumping anything out
did it 2 times and never again, restarted a few times, also waited a long time

**Comment by enjoy2000** [comment]
Maybe your list is too rare lol.

It won’t post anything if there is no pokemon

**Comment by Navyguy330** [comment]
I mean i only added to the ones you posted.  it has nearly 35 pokemon. none of the legendaries.   Dragonits, blastoise, muk, dragonair, venusaur, charizard, vaporeon etc etc.

I mean they pop up enough normally. i am not sure how that tracker works, if its only one location etc.

**Comment by Navyguy330** [comment]
I think trackemon is just down

**Comment by Navyguy330** [comment]
ok working now, it wont work at 2 seconds, but at 1 it will

**Comment by enjoy2000** [comment]
updated
