### ISSUE TITLE
this damn thing is missing WAY to many things that are not even CLOSE ????

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#48]
http://prntscr.com/c0gjt4  should be

WARNING:root:Message has been deleted: Vaporeon
55.8408798253,37.6453347382
xin 6 minutes
Vaporeon
41.9568934107,-87.7021352241 - Author: xMiLlo
WARNING:root:Message has been deleted: Snorlax 35.6594664103, 139.750314601 - Author: Nirvatsh

shouldnt be

Message has been deleted: 35.6594664103,139.750314601  Snorlax - Author: david
Message has been deleted: 41.0340366195, 28.9172445472 Snorlax 96iv - Author: Pi
nkTorpedo
Message has been deleted: Snorlax 96IV 51.5034807353, -0.1288290618653 - Author:
 rebelrod
Message has been deleted: 51.5034807353, -0.1288290618653 snorlax 96iv - Author:
 Fex
Message has been deleted: Snorlax 96IV 51.5034807353, -0.1288290618653 - Author:
 rebelrod
Message has been deleted: snorlax 51.5034807353, -0.1288290618653 iv 96 - Author
: an71nk

shouldnt be??  wtf is going on.

**Comment by Navyguy330** [comment]
http://prntscr.com/c0gkiv


its not even chatting that fast, I have ONE bot for that whole channel

**Comment by Navyguy330** [comment]
is there anyway to monitor more than maybe the very last message? maybe the last ten incase it misses it???

**Comment by enjoy2000** [comment]
There is space in lat/long

**Comment by Navyguy330** [comment]
It shouldn't delete post that are that close.  I mean one space is not a
biggie lol

**Comment by Navyguy330** [comment]
Also it keeps deleting  snorlax ones a lot.
