### ISSUE TITLE
Please allow additional formats

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#53]
Please allow it to have no or several extra spaces between the chords ,.    As well as before or after he Pokemon name / IV and number.

Please also allow to have Pokemon name on an extra line.

Please fix it removing snorlax all the time.

**Comment by enjoy2000** [comment]
Remove `no` in your blacklist config. LOL

**Comment by Navyguy330** [comment]
Oh wow. Lol u may be right

**Comment by Navyguy330** [comment]
But sometimes that gets thru any reason why it allows some?  Just being
slow??

**Comment by enjoy2000** [comment]
Slow is only reason, miss messages.
