### ISSUE TITLE
After doing git pull and pip install

### ISSUE THREAD

**Issue by nuketownhf** [enjoy2000/discord-pokemon-go-snipe-bot#54]
http://i.imgur.com/dcGLcd4.png
Back here O.o ._.
Maybe its because I couldnt do git clone git@github.com:enjoy2000/discord-pokemon-go-snipe-bot.git
and used zip then? It gave me authentication error when using this above

**Comment by enjoy2000** [comment]
Use https then `https://github.com/enjoy2000/discord-pokemon-go-snipe-bot.git`
Still syntax problem in `config.json` i think

**Comment by nuketownhf** [comment]
Wow it worked, logged in and posted. I guess I only had a typo in coordbot channel because I had a capital C in it. 
I put in eevee in configs etc but the bot does nothing
btw. deleting works though , you are a boss mate :P
