### ISSUE TITLE
Trackemon stops after the first output

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#58]
It will output after you run it, but even the console shows the links etc. but it never prints anything else out after the inital one.

have maybe 30 pokemon  timer is set at 1second

**Comment by enjoy2000** [comment]
I removed the `multiple` with pokemon list, change `delay` config back to normal please. And the scrawler is not stable enough, need more test I think. Will do tmr. It's late here.

**Comment by Navyguy330** [comment]
What you mean change to normal ?  Like how is it done ?  Since the Pokemon
are only there for a short time what is a good delay?  I mean if it saves
up until the delay then posts them all rather than as they come in,. Then
most of them will all be outdated by the time they post.

**Comment by enjoy2000** [comment]
Nope, it post right after getting results from api.

Delay is the time between finish scrawling with starting new one.

**Comment by pogoKA** [comment]
@enjoy2000  scrawl is not posting [Expires in: 148 seconds]

**Comment by Navyguy330** [comment]
Yeah I put it to 35 delay but it never posts.  Now not even the first time
lol

**Comment by nuketownhf** [comment]
It post only 1 Arcanine and that's all :/

**Comment by am3yar0ra** [comment]
@nuketownhf Can you help me with the setup please ?

**Comment by enjoy2000** [comment]
updated
