### ISSUE TITLE
Instead of only looking for numbers

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#6]
can I get a mod that would look at the config for a list and use ony those (so a list of all 151 pokemon) and of course the nuymbers and letters IV and all esle gets deleted?

**Comment by enjoy2000** [comment]
Ok updated

**Comment by Navyguy330** [comment]
thanks  also It keeps deleting message from our other bots, even though I have except "bots" and "Bot"

**Comment by enjoy2000** [comment]
Your group is "Bots"
