### ISSUE TITLE
pokemon-go map site

### ISSUE THREAD

**Issue by pogoKA** [enjoy2000/discord-pokemon-go-snipe-bot#66]
https://pokezz.com/
http://spawns.mazbron.net/
https://pmap.kuku.lu/
https://skiplagged.com/pokemon/
http://maps.pokemongo.id/

**Comment by Azndee2** [comment]
do i just replace th trakemon in the config with on of the name?

**Comment by ameyarora** [comment]
http://skiplagged.com/api/pokemon.php?address=central%20park,%20new%20york,%20ny
