### ISSUE TITLE
Problem starting bot

### ISSUE THREAD

**Issue by LiliumElfenLIED** [enjoy2000/discord-pokemon-go-snipe-bot#75]
Hi men,

First, really goob job for your sharing :).

But i have one problem,

I followed the "get starting" I add my bot with the button " https://discordapp.com/oauth2/authorize?client_id=CLIENT_ID&scope=bot&permissions=0" while walking niquel but when I want Lence any command beginning with " python 3" I have a cmd error: Python 3 B 'is not a recognized command .... " and the ocnsole python : File "<stdin>", line 1      python3 bot.py     SyntaxError: invalid syntax

What to do ? Sisnon possible to have a video tutorial to install this? , Moin only if I manage to fix everything so I can make one if you shouaiter .

**Comment by enjoy2000** [comment]
Try with `python bot.py`.

Those commands are for unix\* so if u use windows, just install `python 3.5+` and try with above command

**Comment by LiliumElfenLIED** [comment]
I'm using Windows, and i'm the lasted version (3.5.2), but with your command "python bot.py" does'nt work :/ i'm damn or i'm bad x) ?
