### ISSUE TITLE
Something broke, its removing too much

### ISSUE THREAD

**Issue by Navyguy330** [enjoy2000/discord-pokemon-go-snipe-bot#9]

**Comment by enjoy2000** [comment]
The message need to be in format `Lat/Long Pokemon_name IV`
So the pokemon name must be exact and have IV or iv word there :D

**Comment by Navyguy330** [comment]
ok
what about removing eiditng or delting posts with EXTRA info?
people are posting that then other BS on the end?
anyway to edit messages to remove anything else?

**Comment by Navyguy330** [comment]
also can we get teh log back in the bot? it was nice to see who was spamming shit that you cant see right away

**Comment by Navyguy330** [comment]
btw Lat/Long Pokemon_name IV  you mean Lat,Long Pokemon_name IV##(or##IV)  right?   not lat / long?

**Comment by enjoy2000** [comment]
Yes

**Comment by enjoy2000** [comment]
I mean lat,long

**Comment by enjoy2000** [comment]
We can edit messages or reply to them.

About the `log` I'm working on it with worker to get data from `pokesniper`

**Comment by Navyguy330** [comment]
------
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 275, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "bot.py", line 52, in on_message
    await client.delete_message(message)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 934, in delete_message
    yield from self.http.delete_message(channel.id, message.id, guild_id)
  File "C:\Users\Adam\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\http.py", line 135, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Message

**Comment by Navyguy330** [comment]
kk cool oops  didnt mean to paste that here but that just pooped up recently config error?

**Comment by Navyguy330** [comment]
BTW the pokesniper would be great it I can make it post only IV over 90 to one channel and the rest to tthe rare channel. that way the 90IV channel wont see crap lower than that

**Comment by enjoy2000** [comment]
But the json file u gave me doesn't have IV data

**Comment by Navyguy330** [comment]
i know
i have people that manually place their finds as well but not everyone posts the IV, I just wanteds it to keep posts that had pokemon and coord, AND IV not ONLY ones with all three

**Comment by enjoy2000** [comment]
Done it anw, u can pull it now.
